### ISSUE TITLE
Create `oscd-filtered-list` based on `filtered-list`

### ISSUE THREAD

**Issue by ca-d** [openscd/oscd-filtered-list#1]
As a plugin author and maintainer of already existing plugins, I need to have `open-scd`s `filtered-list` available through nmp.

- slot right and left to add filter icon buttons

**Requirements:**
- move `filtered-list` to `oscd-filtered-list` repo
- change tag name to `oscd-filtered-list`
- do !NOT! extend from `mwc-list` but use it in the `render` method
- add properties

| name | type | description |
|---|---|---|
| searchFieldLabel | string | text on the filter textbox |
| disableCheckAll | boolean | disable the "check all" button |
| filter | string | the current value of the filter textbox |
| wrapFocus | boolean | whether focus wraps around the end and beginning of the list |
| multi | boolean | multi-select |
| activatable | boolean | color icons permanently on clicking |
| @action | event | fired before selection is made (find out: is this actually needed?) |
| @selected | event | fired after selection is made |

TODO: search codebase for instances of `filtered-list` usage and add any properties/events/methods used that are not listed here.

- propagate `selected` event for any changes on `maybeValue`
- propagate `...` event for any changes on `...`
- add screenshot tests
- add storybook

**Additional Information**
This web-component is used pretty much everywhere in the software

**Comment by Sander3003** [comment]
Almost done; Still todo: some testing

**Comment by Sander3003** [comment]
The documentation needs to be added in the readme.md
